!!com.sunrise.jdl.generator.config.GeneratorConfig

jdlConfig:
  mapStruct: true
  paginateType: infinite-scroll
  generateServiceFor:
    - all
  sourceFolder: ./csv-source-folder
  targetFile: entities.jh
  targetResourceFolder: ./i8n
