!!com.sunrise.jdl.generator.ui.UIGenerateParameters

entitiesPath: ./csv-resource-folder
actionsPath: ./csv-resource-folder
targetPath: ./templates-folder
translationPath: partnerGatewayApp.partnerDocuments
titlePath: partnerGatewayApp.partnerDocuments<ENTITY_NAME>.home.title
registryCode: userRegistry
useEntityName: false
microservice: partnerDocuments
pluralTranslations: false
pluralPresentations: true
pluralSearchURL: true
additionalFieldsTranslationPath: additionalFields
additionalFields:
  - fieldName: status
    fieldType: Status
    fieldLength: '12'
    fieldLabel: Статус
    jdlType: true
    required: false
    hidden: true
  - fieldName: number
    fieldType: String
    fieldLength: '50'
    fieldLabel: Номер
    jdlType: true
    required: false
    hidden: true
  - fieldName: archive
    fieldType: Boolean
    fieldLength: '6'
    fieldLabel: Архив
    jdlType: true
    required: false
    hidden: true
  - fieldName: operation
    fieldType: String
    fieldLength: '15'
    fieldLabel: Операция
    jdlType: true
    required: false
    hidden: true
  - fieldName: documentClassLabel
    fieldType: String
    fieldLength: '25'
    fieldLabel: Вид
    jdlType: true
    required: false
    hidden: true
projectionsInfoes:
  - name: New
    order: 1
    filters:
      - field: archive
        values:
          - 'false'
      - field: status
        values:
          - NEW
  - name: Inner
    order: 2
    filters:
      - field: status
        values:
          - ACCEPTED
          - REJECTED
          - REVIEW
  - name: Archive
    order: 3
    filters:
      - field: archive
        values:
          - 'true'
